-- Common channel layer schema.
-- Run with psql against the external PostgreSQL endpoint, not through a pod.
-- Historical UUIDv7 values are generated by scripts/db/002-backfill-common-layer.mjs
-- with the uuid package. The database schema deliberately does not synthesize IDs.

\set ON_ERROR_STOP on

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS common_user (
  common_user_id uuid PRIMARY KEY,
  channel varchar(64) NOT NULL,
  display_name varchar(256),
  avatar_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS common_conversation (
  common_conversation_id uuid PRIMARY KEY,
  channel varchar(64) NOT NULL,
  scope varchar(16) NOT NULL,
  display_name varchar(256),
  avatar_url text,
  member_count integer,
  is_active boolean NOT NULL DEFAULT true,
  attachment_policy jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_common_conversation_channel_scope
  ON common_conversation(channel, scope);

CREATE TABLE IF NOT EXISTS common_message (
  common_message_id uuid PRIMARY KEY,
  channel varchar(64) NOT NULL,
  common_conversation_id uuid NOT NULL REFERENCES common_conversation(common_conversation_id),
  common_user_id uuid REFERENCES common_user(common_user_id),
  sender_display_name varchar(256),
  role varchar(20) NOT NULL,
  content jsonb NOT NULL DEFAULT '[]'::jsonb,
  content_text text,
  common_root_message_id uuid,
  common_reply_message_id uuid,
  -- 这条消息点了谁的名，按公共层 id。NULL 和 '{}' 是两件事：NULL = 没人算过，
  -- '{}' = 算过、确实谁都没点。所以不能 NOT NULL、不能给默认值。
  mentioned_common_user_ids uuid[],
  scope varchar(16) NOT NULL,
  message_type varchar(30),
  bot_name varchar(50),
  response_id varchar(100),
  -- 这一行是赤尾哪一次主动开口的产物（出站信封 message_id 里 `proactive:` 前缀
  -- 之后那个 uuid）。NULL = 没记过，跟"确实不是主动发的"是两件事。
  agent_outbound_id uuid,
  -- 这一行在渠道上被撤掉的时刻，撤成功才填。NULL = 没撤过或者还没撤掉。
  recalled_at timestamptz,
  event_time bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 上面是 CREATE TABLE IF NOT EXISTS，对已经存在的表整段是 no-op。这三列是建表
-- 之后加的，所以老库要靠下面这段补齐；新库执行到这里三列已经在了，也是 no-op。
-- 两边的可空性和"无默认值"必须跟 CREATE TABLE 里逐字一致 —— 这三列的读法都是
-- "NULL 表示没算过 / 没记过 / 没撤过"，给了默认值就再也分不开。
ALTER TABLE common_message
  ADD COLUMN IF NOT EXISTS mentioned_common_user_ids uuid[],
  ADD COLUMN IF NOT EXISTS agent_outbound_id uuid,
  ADD COLUMN IF NOT EXISTS recalled_at timestamptz;

CREATE INDEX IF NOT EXISTS idx_common_message_conversation_time
  ON common_message(common_conversation_id, event_time);
CREATE INDEX IF NOT EXISTS idx_common_message_user_time
  ON common_message(common_user_id, event_time);
CREATE INDEX IF NOT EXISTS idx_common_message_response_id
  ON common_message(response_id);
CREATE INDEX IF NOT EXISTS idx_common_message_root_time
  ON common_message(common_root_message_id, event_time);
-- 前缀是 ix_ 不是 idx_：物理表上已经存在的那个由 agent-service 的 SQLAlchemy
-- `index=True` 建出来，默认命名是 ix_<表>_<列>。这里跟着它写，是为了让本脚本、
-- 两侧 ORM 实体和已有的物理索引指的是同一个对象；写成 idx_ 就会在同一列上出现
-- 第二个索引。
CREATE INDEX IF NOT EXISTS ix_common_message_agent_outbound_id
  ON common_message(agent_outbound_id);

CREATE TABLE IF NOT EXISTS common_agent_response (
  response_id uuid PRIMARY KEY,
  session_id varchar(100) NOT NULL,
  trigger_common_message_id uuid NOT NULL REFERENCES common_message(common_message_id),
  common_conversation_id uuid NOT NULL REFERENCES common_conversation(common_conversation_id),
  bot_name varchar(50),
  persona_id varchar(50),
  response_type varchar(30) NOT NULL DEFAULT 'reply',
  replies jsonb NOT NULL DEFAULT '[]'::jsonb,
  response_text text,
  agent_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  safety_status varchar(20) NOT NULL DEFAULT 'pending',
  safety_result jsonb,
  status varchar(20) NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_common_agent_response_session UNIQUE(session_id)
);

CREATE TABLE IF NOT EXISTS common_bot_presence (
  common_conversation_id uuid NOT NULL REFERENCES common_conversation(common_conversation_id),
  bot_name varchar(50) NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(common_conversation_id, bot_name)
);
CREATE INDEX IF NOT EXISTS idx_common_bot_presence_bot
  ON common_bot_presence(bot_name);

CREATE TABLE IF NOT EXISTS lark_message (
  om_id varchar(256) PRIMARY KEY,
  common_message_id uuid NOT NULL UNIQUE REFERENCES common_message(common_message_id),
  chat_id varchar(256) NOT NULL,
  sender_open_id varchar(256),
  sender_union_id varchar(256),
  root_om_id varchar(256),
  reply_om_id varchar(256),
  message_type varchar(64) NOT NULL,
  raw_event jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lark_message_chat_id ON lark_message(chat_id);

ALTER TABLE lark_user_open_id
  ADD COLUMN IF NOT EXISTS common_user_id uuid;
CREATE INDEX IF NOT EXISTS idx_lark_user_open_id_common_user_id
  ON lark_user_open_id(common_user_id);

ALTER TABLE lark_base_chat_info
  ADD COLUMN IF NOT EXISTS common_conversation_id uuid;
CREATE UNIQUE INDEX IF NOT EXISTS uq_lark_base_chat_info_common_conversation_id
  ON lark_base_chat_info(common_conversation_id)
  WHERE common_conversation_id IS NOT NULL;
