apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: prod
  labels:
    app: mongodb
    tier: infra
spec:
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
      protocol: TCP
    - name: metrics
      port: 9216
      targetPort: 9216
      protocol: TCP
