apiVersion: v1
kind: Service
metadata:
  name: forward-proxy
  namespace: prod
  labels:
    app: forward-proxy
    tier: infra
spec:
  selector:
    app: forward-proxy
  ports:
    - name: proxy
      port: 8888
      targetPort: 8888
      protocol: TCP
