apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: paas-engine
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: paas-engine
      lane: prod
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: api-gateway
      lane: prod
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lite-registry
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app: lite-registry
      lane: prod
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
